### ISSUE TITLE
Conda forge package dependencies differ from base package dependencies

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/geosnap-feedstock#24]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The dependencies for this package have diverged from what the package reports as dependecies.  For example, on conda-forge, this package has the outdated package `spenc` as a dependency, when it has been removed from the dependencies of the actual geosnap package.  Additionally, a number of the required versions of dependencies do not match those of geosnap in github.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by knaaptime** [comment]
thanks! yes, the deps here are way out of date. I'll make sure that gets fixed in the next release

**Comment by jGaboardi** [comment]
@knaaptime Let's look at this for the `v0.12.0 release, too.

**Comment by knaaptime** [comment]
yeah, im waiting for the bot's PR to hit, then i'll edit the deps

**Comment by jGaboardi** [comment]
@knaaptime , so this issue can now be closed, correct?
